---
title: "Introduction to org"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Introduction to org}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Concept 

The concept behind `org` is fairly simple - most analyses have three main sections:

- Code
- Results
- Data

Each of these sections has unique requirements.

Code should:

- Be version controlled.
- Be publically accessible.
- Have a single analysis pipeline detailing all steps of data cleaning, analysis, and result generation.

Results should:

- Be immediately shared with close collaborators.
- Save each set of results and make them accessible to track changes over time.

Data should:

- Be encrypted (if sensitive).
- Not stored on the cloud (if sensitive).

## Code

### org::initialize_project

`org::initialize_project` takes in 2+ arguments. It then saves its results (i.e., folder locations) in `org::project`, which you will use in all subsequent code.

- `home`: Location of `Run.R` and the `R/` folder. Accessible via `org::project$home` (but you will rarely need this).
- `results`: Results folder. Creates a folder inside `results` with today's date, accessible via `org::project$results_today` (this is where you will store all of your results). Because the folder's name is today's date, this means that it automatically archives one copy of results per day. This allows you and your collaborators to easily check and see how the results have changed over time.
- `...`: Specify other folders if needed, which will also be accessible via `org::project` (e.g., `data_raw` for raw data, `data_clean` for clean data).

### Run.R 

`Run.R` will be your main file, sequentially running through every part of your analysis:

- Data cleaning
- Analysis
- Result generation

All sections of code should be encapsulated in functions living in the `R/` folder.

You should not have any other main files, as this creates confusion when you need to return to your code two years later. However, you can have different versions of `Run.R` (e.g., `Run_v01.R`, `Run_v02.R`), where it is implicitly understood that the later versions supersede the earlier ones. Once `Run_v03.R` exists, `Run_v02.R` is considered deprecated and is only retained for historical archival purposes, not for active use.

All sections of code (e.g. data cleaning, analyses for table 1, analyses for table 2, result generation for table 1, sensitivity analysis 1, etc) will be encapsulated in functions that live in the `R` folder.

### Example `Run.R`

```
# Define the following 'special' locations:
# 'home' (i.e. Run.R and R/ folder)
# 'results' (i.e. A folder with today's date will be created here)

# Define any other locations you want:
# 'raw' (i.e. raw data)

org::initialize_project(
  env = .GlobalEnv,
  home = "/git/analyses/2019/analysis3/",
  results = "/dropbox/analyses_results/2019/analysis3/"
  data_raw = "/data/analyses/2019/analysis3/"
)

# Describe changes in archived results day-to-day
# Save this information in a text file in the `org::project$results` folder
txt <- glue::glue("
  2019-01-01:
    Included:
    - Table 1
    - Table 2
  
  2019-02-02:
    Changed Table 1 from mean -> median
  
", .trim=FALSE)

org::write_text(
  txt = txt,
  file = fs::path(org::project$results, "info.txt")
)

library(data.table)
library(ggplot2)

# This function accesses data located in org::project$data_raw
d <- clean_data()

# These functions save results to org::project$results_today
table_1(d)
figure_1(d)
figure_2(d)
```

### R/

All of your functions should be defined in `org::project$home/R`. The function `org::initialize_project` automatically sources all R scripts in `org::project$home/R`.

## Versioning Research Articles

When writing a research article, multiple versions are often required (initial submission, followed by multiple resubmission variants based on the recommendations of peer reviewers). Rename `Run.R` and `R/` to include the submission date for each version to preserve the code that produced the results for every submission.

On the initial submission of the article, rename `Run.R` and `R/` to `Run_YYYY_MM_DD_submission_1.R` and `R_YYYY_MM_DD_submission_1/` (YYYY_MM_DD should be replaced with year, month, and date).

When making adjustments for the resubmission, rename the relevant files/folders to `run_YYYY_MM_DD_submission_2.R` and `R_YYYY_MM_DD_submission_2/` (YYYY_MM_DD should be replaced with year, month, and date).

In doing so, you successfully preserve all of your code that produced the results for every submission, allowing you to easily ensure that all changes are deliberate and intentional.

## Solutions

### Best Practice

Store code in GitHub, data locally in an encrypted volume, and results on Dropbox with each day's results in a different folder.

```
# code goes here:
git
  +-- analyses
             +-- 2018
             |      +-- analysis_1 <- org::project$home
             |      |           +-- Run.R
             |      |           +-- R
             |      |                  +-- clean_data.R
             |      |                  +-- descriptives.R
             |      |                  +-- analysis.R
             |      |                  +-- figure_1.R
             |      +-- analysis_2 <- org::project$home
             |                  +-- Run.R
             |                  +-- R
             |                         +-- clean_data.R
             |                         +-- descriptives.R
             |                         +-- analysis.R
             |                         +-- figure_1.R
             +-- 2019
                    +-- analysis_3 <- org::project$home
                                +-- Run.R
                                +-- R
                                       +-- clean_data.R
                                       +-- descriptives.R
                                       +-- analysis.R
                                       +-- figure_1.R
                                       
# results goes here:
dropbox
  +-- analyses_results
             +-- 2018
             |      +-- analysis_1 <- org::project$results
             |      |           +-- 2018-03-12 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- figure_1.png
             |      |           +-- 2018-03-15 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- figure_1.png
             |      |           +-- 2018-03-18 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- figure_1.png
             |      |           |            +-- figure_2.png
             |      |           +-- 2018-06-18 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- table_2.xlsx
             |      |           |            +-- figure_1.png
             |      |           |            +-- figure_2.png
             |      +-- analysis_2 <- org::project$results
             |      |           +-- 2018-06-09 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- figure_1.png
             |      |           +-- 2018-12-15 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- figure_1.png
             |      |           +-- 2019-01-18 <- org::project$results_today
             |      |           |            +-- table_1.xlsx
             |      |           |            +-- figure_1.png
             |      |           |            +-- figure_2.png
             +-- 2019
                    +-- analysis_3 <- org::project$results
                    |           +-- 2019-06-09 <- org::project$results_today
                    |           |            +-- table_1.xlsx
                    |           |            +-- figure_1.png
                    |           +-- 2019-12-15 <- org::project$results_today
                    |           |            +-- table_1.xlsx
                    |           |            +-- figure_1.png
                    |           +-- 2020-01-18 <- org::project$results_today
                    |           |            +-- table_1.xlsx
                    |           |            +-- figure_1.png
                    |           |            +-- figure_2.png

# data goes here:
data
  +-- analyses
             +-- 2018
             |      +-- analysis_1 <- org::project$data_raw
             |      |           +-- data.xlsx
             |      +-- analysis_2 <- org::project$data_raw
             |      |           +-- data.xlsx
             +-- 2019
                    +-- analysis_3 <- org::project$data_raw
                                +-- data.xlsx

```

Suggested code for `Run.R`:

```
org::initialize_project(
  env = .GlobalEnv,
  home = "/git/analyses/2019/analysis_3/",
  results = "/dropbox/analyses_results/2019/analysis_3/",
  data_raw = "/data/analyses/2019/analysis_3/"
)
```

### RMarkdown

For a single folder on a shared network drive, without access to GitHub or Dropbox, you can create an RMarkdown document with the following structure:

```
# code goes here:
project_name <- org::project$home
  +-- Run.R
  +-- R
  |      +-- CleanData.R
  |      +-- Descriptives.R
  |      +-- Analysis1.R
  |      +-- Graphs1.R
  +-- paper
  |      +-- paper.Rmd
  +-- results <- org::project$results
  |         +-- 2018-03-12 <- org::project$results_today
  |         |            +-- table1.xlsx
  |         |            +-- figure1.png
  |         +-- 2018-03-12 <- org::project$results_today
  |         |            +-- table1.xlsx
  |         |            +-- figure1.png
  +-- data_raw <- org::project$raw
  |          +-- data.xlsx
```

Suggested code for `Run.R`:

```
# Initialize the project

org::initialize_project(
  env = .GlobalEnv,
  home = "/network/project_name/",
  results = "/network/project_name/results/",
  paper = "/network/paper/",
  raw = "/network/project_name/data_raw/"
)

# do some analyses here

# render the paper

rmarkdown::render(
  input = fs::path(org::project$paper,"paper.Rmd"),
  output_dir = org::project$results_today,
  quiet = F
)
```

### One Folder on a Shared Network Drive Without GitHub Access

If you only have one folder on a shared network drive, without GitHub or Dropbox access, then we suggest the following structure:

```
# code goes here:
project_name <- org::project$home
  +-- Run.R
  +-- R
  |      +-- clean_data.R
  |      +-- descriptives.R
  |      +-- analysis.R
  |      +-- figure_1.R
  +-- results <- org::project$results
  |         +-- 2018-03-12 <- org::project$results_today
  |         |            +-- table_1.xlsx
  |         |            +-- figure_1.png
  |         +-- 2018-03-12 <- org::project$results_today
  |         |            +-- table_1.xlsx
  |         |            +-- figure_1.png
  +-- data_raw <- org::project$data_raw
  |          +-- data.xlsx
```

Suggested code for `Run.R`:

```
org::initialize_project(
  env = .GlobalEnv,
  home = "/network/project_name/",
  results = "/network/project_name/results/",
  data_raw = "/network/project_name/data_raw/"
)
```

## Naming Conventions for Path Components

Let us consider the file `/home/richard/test.src`

| Component              | Name                      |
|------------------------|---------------------------|
| /home/richard/test.src | Absolute (file)path       |
| richard/test.src       | Relative (file)path       |
| /home/richard/         | Absolute (directory) path |
| ./richard/             | Relative (directory) path |
| richard                | Directory                 |
| test.src               | Filename                  |

A path is a location in a directory structure. Filenames only include
information about the name of the file. Directories only include
information about the name of the directory. Filepaths are paths that
specify the location of a file.
